providers = ["python"]

[phases.setup]
aptPkgs = ["shellcheck"]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g eslint@9 @typescript-eslint/parser @typescript-eslint/eslint-plugin",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []
