"""pre-commit 관측면 가드의 계약 (backlog R23).

🔴 이 파일의 본체는 **"advisory 인데 공허하지 않은가"** 다. 항상 exit 0 인 검사는 아무것도
보고하지 않아도 통과한다 — 그러면 관측면이 있다고 **믿으면서** 관측이 0 인 상태가 된다.
그래서 판정 함수(`hook_is_precommit`)의 양성/음성 통제와 **배선**을 따로 단언한다.

The point is that an always-exit-0 check can be vacuous: it passes while reporting nothing.
So the verdict function gets positive/negative controls and the wiring is asserted separately.
"""
import json
import sys
from pathlib import Path

import pytest

import scripts.check_precommit_installed as mod
from tests.unit.scripts._wiring_shape import any_invokes

_ROOT = Path(__file__).resolve().parents[3]

NL = "\n"


def _generated_hook(hook_type: str, interpreter: str | None = None) -> str:
    """pre-commit 이 **실제로 생성하는** 훅 본문 (2026-08-06 실물 생성 후 복제).

    합성 픽스처를 손으로 지어내면 판정이 실제 산출물과 갈라진다 — 이 문자열은
    `pre-commit 4.6.1` 이 임시 리포에 만든 파일에서 그대로 옮긴 것이다.
    """
    py = interpreter if interpreter is not None else sys.executable
    return (
        "#!/bin/sh" + NL
        + "# File generated by pre-commit: https://pre-commit.com" + NL
        + "# ID: 138fd403232d2ddd5efb44317e38bf03" + NL
        + "# start templated" + NL
        + "INSTALL_PYTHON='" + py + "'" + NL
        + "ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=" + hook_type + ")" + NL
        + "# end templated" + NL
        + 'if [ -x "$INSTALL_PYTHON" ]; then' + NL
        + '    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"' + NL
        + "fi" + NL
    )


def _install(hooks: Path, *types: str, interpreter: str | None = None) -> Path:
    hooks.mkdir(exist_ok=True)
    for t in types:
        (hooks / t).write_text(_generated_hook(t, interpreter), encoding="utf-8")
    return hooks


# ── 판정 함수 (양성/음성 통제) ───────────────────────────────────────────


def test_reports_installed_when_hook_self_identifies(tmp_path):
    """양성 통제 — pre-commit 이 **실제로 생성한** 형태의 훅은 활성으로 본다."""
    assert mod.hook_is_precommit(_install(tmp_path / "hooks", "pre-commit")) is True


# 🔴 실측된 defeat 4형태 (2026-08-06). 구 판정 `"pre-commit" in text` 는 아래 셋을
#    **전부 True** 로 봤다 — 즉 *아무것도 막지 않는 훅*이 "계층 활성" 으로 보고됐다.
_NEUTRALISED = {
    "비활성 스텁": "#!/bin/sh" + NL + "exit 0  # pre-commit disabled" + NL,
    "메시지만 출력": "#!/bin/sh" + NL + "echo 'pre-commit skipped'" + NL,
    "경로만 언급": "#!/bin/sh" + NL + ": .git/hooks/pre-commit" + NL,
    "무관한 도구": "#!/bin/sh" + NL + "echo husky" + NL,
}


@pytest.mark.parametrize(("label", "body"), list(_NEUTRALISED.items()))
def test_neutralised_hook_is_not_counted_as_installed(tmp_path, label: str, body: str):
    """🔴 중화된 훅을 '설치됨' 으로 세면 관측자가 거짓말을 한다.

    구현이 bare substring 이던 시절 이 4형태 중 3형태가 통과했다(실측). 판정을
    pre-commit 생성물의 **구조**(`hook-impl` + `-mpre_commit`)에서 끌어와 봉인한다.
    """
    hooks = tmp_path / "hooks"
    hooks.mkdir()
    (hooks / "pre-commit").write_text(body, encoding="utf-8")
    assert mod.hook_is_precommit(hooks) is False, "중화된 훅을 활성으로 판정했다: " + label


def test_hook_with_a_dead_interpreter_is_not_healthy(tmp_path):
    """🔴 훅은 절대 인터프리터 경로를 박아 넣는다 — 그 경로가 죽으면 훅도 죽는다.

    형태는 멀쩡한데 실행만 실패하는 상태를 '설치됨' 으로 보면 안 된다.
    """
    hooks = _install(tmp_path / "hooks", "pre-commit",
                     interpreter=str(tmp_path / "no-such-python.exe"))
    assert mod.hook_is_precommit(hooks) is False


def test_hook_declaring_another_type_is_not_counted(tmp_path):
    """파일명만 바꿔 놓은 훅을 인정하지 않는다 — 선언된 `--hook-type` 으로 판정한다."""
    hooks = tmp_path / "hooks"
    hooks.mkdir()
    (hooks / "pre-commit").write_text(_generated_hook("commit-msg"), encoding="utf-8")
    assert mod.hook_is_precommit(hooks) is False


# ── 부분 설치 (가장 흔하고 가장 조용한 실패) ────────────────────────────


def test_partial_install_is_reported_as_incomplete(tmp_path, monkeypatch, capsys):
    """🔴 `pre-commit install` 만 치면 `commit-msg` 타입이 빠진다.

    그러면 **실제 토큰 유출 사고로 만들어진** `check-commit-msg-secrets` 만 조용히 죽고
    나머지는 설치돼 겉보기에는 "완료" 다. 구 판정은 이 상태를 활성으로 보고했다.
    """
    monkeypatch.setattr(mod, "git_hooks_dir",
                        lambda _r: _install(tmp_path / "hooks", "pre-commit"))
    monkeypatch.setattr(mod, "pre_push_gate_installed", lambda _d: True)
    assert mod.main() == 0
    out = capsys.readouterr().out
    assert "commit-msg" in out, "부분 설치를 완전 설치로 보고했다"
    assert "누락" in out, "무엇이 빠졌는지 말하지 않았다"


def test_both_types_present_reports_active(tmp_path, monkeypatch, capsys):
    """대조군 — 둘 다 있으면 활성으로 보고한다(항상 빨간 배너면 신호가 소음이 된다)."""
    monkeypatch.setattr(
        mod, "git_hooks_dir",
        lambda _r: _install(tmp_path / "hooks", "pre-commit", "commit-msg"))
    monkeypatch.setattr(mod, "pre_push_gate_installed", lambda _d: True)
    assert mod.main() == 0
    assert "활성" in capsys.readouterr().out


def test_required_types_match_the_config():
    """🔴 스크립트의 리터럴 ↔ `.pre-commit-config.yaml` 양방향 대조.

    리터럴로 못박은 이유는 설정에서 유도하면 그 키를 지웠을 때 통과하기 때문이다
    (자기참조 공허화). 대신 갈라지지 않도록 여기서 대조한다.
    """
    import yaml

    declared = yaml.safe_load(
        (_ROOT / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    ).get("default_install_hook_types") or []
    assert set(mod.REQUIRED_HOOK_TYPES) == set(declared), (
        "스크립트 " + str(mod.REQUIRED_HOOK_TYPES) + " 와 설정 " + str(declared) + " 가 갈라졌다"
    )


def test_absent_hook_is_not_installed(tmp_path):
    """🔴 음성 통제 — 파일이 없으면 미설치. 이게 실측된 현재 상태다."""
    hooks = tmp_path / "hooks"
    hooks.mkdir()
    assert mod.hook_is_precommit(hooks) is False


def test_foreign_hook_is_not_counted_as_precommit(tmp_path):
    """🔴 **존재만으로 설치로 세면 안 된다** — 다른 도구가 남긴 훅일 수 있다.

    존재 검사는 이 리포가 반복 지적해 온 fail-open 형태(파일이 있으면 참)라 소유자까지 본다.
    """
    hooks = tmp_path / "hooks"
    hooks.mkdir()
    (hooks / "pre-commit").write_text("#!/bin/sh\necho husky\n", encoding="utf-8")
    assert mod.hook_is_precommit(hooks) is False


def test_none_hooks_dir_is_not_installed():
    """git 이 훅 경로를 못 주면 미설치로 본다(추측 금지)."""
    assert mod.hook_is_precommit(None) is False


def test_git_hooks_dir_resolves_in_this_repo():
    """대조군 — 실제 리포에서 훅 디렉토리를 찾는다(탐지기가 항상 None 이면 공허)."""
    got = mod.git_hooks_dir(_ROOT)
    assert got is not None and got.name == "hooks"


# ── advisory 계약 ────────────────────────────────────────────────────────


def test_main_is_advisory_in_both_states(monkeypatch, capsys, tmp_path):
    """🔴 어떤 상태에서도 exit 0 — 차단하면 새 클론·CI·타 개발자 세션이 막힌다(정책 17).

    동시에 **미설치일 때 실제로 말을 해야** 한다 — 조용한 advisory 는 관측면이 아니다.
    """
    empty = tmp_path / "empty"
    empty.mkdir()
    monkeypatch.setattr(mod, "git_hooks_dir", lambda _r: empty)
    monkeypatch.setattr(mod, "pre_push_gate_installed", lambda _d: True)
    assert mod.main() == 0
    out = capsys.readouterr().out
    assert "gitleaks" in out, "미설치인데 아무 말도 하지 않았다"

    monkeypatch.setattr(
        mod, "git_hooks_dir",
        lambda _r: _install(tmp_path / "hooks", "pre-commit", "commit-msg"))
    assert mod.main() == 0
    assert "활성" in capsys.readouterr().out


def test_path_binary_is_not_required(monkeypatch, capsys, tmp_path):
    """🔴 `pre-commit` 이 PATH 에 없어도 훅은 **정상 동작**한다.

    생성된 훅이 절대 인터프리터 경로를 박아 넣기 때문이다(실물 실측). 구 판정은
    PATH 바이너리를 AND 조건으로 요구해, 이 머신에서 **설치를 성공해도 계속 빨간 배너**를
    냈다 — 무조건 빨강은 정상 빨강과 구별되지 않아 배너 피로로 신호를 죽인다.
    """
    monkeypatch.setattr(
        mod, "git_hooks_dir",
        lambda _r: _install(tmp_path / "hooks", "pre-commit", "commit-msg"))
    monkeypatch.setattr(mod, "pre_push_gate_installed", lambda _d: True)
    monkeypatch.setenv("PATH", str(tmp_path))  # PATH 에 pre-commit 없음
    assert mod.main() == 0
    assert "활성" in capsys.readouterr().out, "PATH 부재를 미설치로 오판했다"


# ── 배선 (실행 관측 — 산문 아님) ─────────────────────────────────────────


def test_wired_to_session_start():
    """🔴 SessionStart 에서 **실제로 실행**되는가 — 배선 없는 관측면은 관측하지 않는다."""
    settings = json.loads((_ROOT / ".claude" / "settings.json").read_text(encoding="utf-8"))
    commands = [
        hook.get("command", "")
        for entry in settings.get("hooks", {}).get("SessionStart", [])
        for hook in entry.get("hooks", [])
    ]
    assert any_invokes(commands, "scripts/check_precommit_installed.py"), (
        f"SessionStart 미배선 — 매 세션 관측이 일어나지 않는다.\n현재 배선: {commands}"
    )


# ──────────────────────────────────────────────────────────────────────────────
# 🔴 pre-push 게이트 관측 축 (2026-08-01 — Grok 설계 검토 `019fbc8e`)
#
# `pre_push_gate.py`(#1258)를 사람이 **기억해서** 돌려야 하는 상태였다. 기억 의존은 이 리포가
# 반복해 고쳐 온 실패 클래스라 자동화가 필요했는데, `.pre-commit-config.yaml` 에
# `stages: [pre-push]` 를 적는 안은 **기각**됐다 — pre-commit 이 그 훅 타입을 따로 설치해야
# 동작하므로, pre-commit 미설치 머신(이 PC 포함)에서는 **한 번도 안 도는 가드**가 된다.
#
# 로컬 훅은 git 이 추적하지 않으므로 리포는 **강제할 수 없고 관측만** 할 수 있다.
# 그 관측이 이 축이다. advisory(비차단) 유지 — 정책 17.
# ──────────────────────────────────────────────────────────────────────────────

def test_pre_push_gate_detected_only_when_it_calls_the_runner(tmp_path):
    """🔴 존재만으로 인정하지 않는다 — 다른 도구가 남긴 훅·빈 파일은 게이트가 아니다."""
    hooks = tmp_path / "hooks"
    hooks.mkdir()

    assert mod.pre_push_gate_installed(hooks) is False, "훅 파일이 없는데 인정했다"

    hook = hooks / "pre-push"
    hook.write_text("#!/bin/sh\necho 'some other tool'\n", encoding="utf-8")
    assert mod.pre_push_gate_installed(hooks) is False, "러너를 부르지 않는 훅을 인정했다"

    hook.write_text("#!/bin/sh\npy -3 scripts/pre_push_gate.py\n", encoding="utf-8")
    assert mod.pre_push_gate_installed(hooks) is True


def test_pre_push_gate_absent_hooks_dir_is_not_wired(tmp_path):
    """🔴 fail-closed — 훅 디렉토리를 못 찾으면 '있다' 고 말하지 않는다."""
    assert mod.pre_push_gate_installed(None) is False
    assert mod.pre_push_gate_installed(tmp_path / "nope") is False


def test_missing_pre_push_gate_is_announced(monkeypatch, capsys, tmp_path):
    """🔴 없으면 **말한다** — 조용하면 관측면이 아니다."""
    monkeypatch.setattr(mod, "pre_push_gate_installed", lambda hooks_dir: False)
    monkeypatch.setattr(mod, "git_hooks_dir", lambda root: tmp_path)

    assert mod.main() == 0, "advisory 여야 한다(정책 17) — 차단 금지"
    out = capsys.readouterr().out
    assert "pre-push 게이트 훅이 없습니다" in out
    assert "pre_push_gate.py" in out, "복구 방법이 없으면 고지가 무용하다"


def test_present_pre_push_gate_is_silent(monkeypatch, capsys, tmp_path):
    """있으면 조용해야 한다 — 매번 떠들면 배너 피로로 다른 경고까지 묻힌다."""
    monkeypatch.setattr(mod, "pre_push_gate_installed", lambda hooks_dir: True)
    monkeypatch.setattr(
        mod, "git_hooks_dir",
        lambda root: _install(tmp_path / "hooks", "pre-commit", "commit-msg"))

    assert mod.main() == 0
    assert "pre-push 게이트 훅이 없습니다" not in capsys.readouterr().out


def test_config_installs_both_hook_types_by_default():
    """🔴 `.pre-commit-config.yaml` 의 `default_install_hook_types` 가 두 타입을 모두 담는다.

    ## 왜 이 단언이 필요한가 (2026-08-17 실측 · 정책 4)

    `.claude/rules/guards.md` 와 `docs/runbooks/secret-prevention.md` 가
    **「맨 `pre-commit install` 이 두 타입을 함께 설치한다」** 고 단언하고, 그 근거로
    문서 8지점에서 `--hook-type` 처방을 걷어냈다. 그 단언이 참인 이유는 오직 이 키 하나다.

    빈 저장소 4종 실측:

    | 형태 | 결과 |
    |---|---|
    | `pre-commit install` | pre-commit + commit-msg |
    | `--hook-type commit-msg` 단독 | **commit-msg 만** |
    | `--hook-type` 2종 명시 | 둘 다 |
    | **이 키를 제거한 뒤 맨 `install`** | **pre-commit 만** ← 뮤테이션 red |

    즉 이 줄이 사라지면 문서 8지점이 조용히 거짓이 되고, 실제 토큰 유출 사고로 만들어진
    `check-commit-msg-secrets` 가 새 머신에서 설치되지 않는다. 산문으로만 지키면 안 되는 자리다.

    The docs stopped prescribing `--hook-type` because this key installs both; if it is
    removed, that guidance silently becomes false and the commit-msg hook never installs.
    """
    text = (_ROOT / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    declared = [
        line for line in text.splitlines()
        if line.startswith("default_install_hook_types:")
    ]
    assert declared, (
        "`.pre-commit-config.yaml` 에 `default_install_hook_types` 가 없다 — "
        "맨 `pre-commit install` 은 pre-commit 타입만 설치하고, "
        "guards.md·secret-prevention.md 의 「두 타입을 함께 설치한다」가 거짓이 된다."
    )
    for hook_type in mod.REQUIRED_HOOK_TYPES:
        assert hook_type in declared[0], (
            f"`default_install_hook_types` 에 {hook_type!r} 가 없다: {declared[0]!r}\n"
            f"  REQUIRED_HOOK_TYPES = {mod.REQUIRED_HOOK_TYPES}"
        )
