"""pre-commit 관측면 가드의 계약 (backlog R23).

🔴 이 파일의 본체는 **"advisory 인데 공허하지 않은가"** 다. 항상 exit 0 인 검사는 아무것도
보고하지 않아도 통과한다 — 그러면 관측면이 있다고 **믿으면서** 관측이 0 인 상태가 된다.
그래서 판정 함수(`hook_is_precommit`)의 양성/음성 통제와 **배선**을 따로 단언한다.

The point is that an always-exit-0 check can be vacuous: it passes while reporting nothing.
So the verdict function gets positive/negative controls and the wiring is asserted separately.
"""
import json
from pathlib import Path

import scripts.check_precommit_installed as mod
from tests.unit.scripts._wiring_shape import any_invokes

_ROOT = Path(__file__).resolve().parents[3]


# ── 판정 함수 (양성/음성 통제) ───────────────────────────────────────────


def test_reports_installed_when_hook_self_identifies(tmp_path):
    """양성 통제 — pre-commit 이 생성한 훅은 자기 식별 문자열을 담는다."""
    hooks = tmp_path / "hooks"
    hooks.mkdir()
    (hooks / "pre-commit").write_text("#!/bin/sh\n# generated by pre-commit\n", encoding="utf-8")
    assert mod.hook_is_precommit(hooks) is True


def test_absent_hook_is_not_installed(tmp_path):
    """🔴 음성 통제 — 파일이 없으면 미설치. 이게 실측된 현재 상태다."""
    hooks = tmp_path / "hooks"
    hooks.mkdir()
    assert mod.hook_is_precommit(hooks) is False


def test_foreign_hook_is_not_counted_as_precommit(tmp_path):
    """🔴 **존재만으로 설치로 세면 안 된다** — 다른 도구가 남긴 훅일 수 있다.

    존재 검사는 이 리포가 반복 지적해 온 fail-open 형태(파일이 있으면 참)라 소유자까지 본다.
    """
    hooks = tmp_path / "hooks"
    hooks.mkdir()
    (hooks / "pre-commit").write_text("#!/bin/sh\necho husky\n", encoding="utf-8")
    assert mod.hook_is_precommit(hooks) is False


def test_none_hooks_dir_is_not_installed():
    """git 이 훅 경로를 못 주면 미설치로 본다(추측 금지)."""
    assert mod.hook_is_precommit(None) is False


def test_git_hooks_dir_resolves_in_this_repo():
    """대조군 — 실제 리포에서 훅 디렉토리를 찾는다(탐지기가 항상 None 이면 공허)."""
    got = mod.git_hooks_dir(_ROOT)
    assert got is not None and got.name == "hooks"


# ── advisory 계약 ────────────────────────────────────────────────────────


def test_main_is_advisory_in_both_states(monkeypatch, capsys):
    """🔴 어떤 상태에서도 exit 0 — 차단하면 새 클론·CI·타 개발자 세션이 막힌다(정책 17).

    동시에 **미설치일 때 실제로 말을 해야** 한다 — 조용한 advisory 는 관측면이 아니다.
    """
    monkeypatch.setattr(mod.shutil, "which", lambda _n: None)
    monkeypatch.setattr(mod, "hook_is_precommit", lambda _d: False)
    assert mod.main() == 0
    out = capsys.readouterr().out
    assert "pre-commit" in out and "gitleaks" in out, "미설치인데 아무 말도 하지 않았다"

    monkeypatch.setattr(mod.shutil, "which", lambda _n: "/usr/bin/pre-commit")
    monkeypatch.setattr(mod, "hook_is_precommit", lambda _d: True)
    assert mod.main() == 0
    assert "활성" in capsys.readouterr().out


def test_main_reports_down_when_binary_present_but_hook_absent(monkeypatch, capsys):
    """🔴 실행파일만 있고 `pre-commit install` 을 안 했으면 **여전히 내려간 것**이다.

    "설치돼 있다" 를 바이너리 존재로만 판정하면 가장 흔한 실패(install 누락)를 놓친다.
    """
    monkeypatch.setattr(mod.shutil, "which", lambda _n: "/usr/bin/pre-commit")
    monkeypatch.setattr(mod, "hook_is_precommit", lambda _d: False)
    assert mod.main() == 0
    assert "내려가" in capsys.readouterr().out


# ── 배선 (실행 관측 — 산문 아님) ─────────────────────────────────────────


def test_wired_to_session_start():
    """🔴 SessionStart 에서 **실제로 실행**되는가 — 배선 없는 관측면은 관측하지 않는다."""
    settings = json.loads((_ROOT / ".claude" / "settings.json").read_text(encoding="utf-8"))
    commands = [
        hook.get("command", "")
        for entry in settings.get("hooks", {}).get("SessionStart", [])
        for hook in entry.get("hooks", [])
    ]
    assert any_invokes(commands, "scripts/check_precommit_installed.py"), (
        f"SessionStart 미배선 — 매 세션 관측이 일어나지 않는다.\n현재 배선: {commands}"
    )
