"""Auto-merge 실패 시 GitHub Issue 자동 생성 — Phase F.3."""
import logging
import httpx
from src.constants import GITHUB_API
from src.github_client.helpers import github_api_headers
from src.shared.http_client import get_http_client

logger = logging.getLogger(__name__)

ISSUE_LABELS = ["scamanager", "auto-merge-failure"]


def _build_issue_body(
    *,
    repo_name: str,
    pr_number: int,
    score: int,
    threshold: int,
    reason: str,
    advice: str,
) -> str:
    """Auto-merge 실패 Issue 본문을 조립한다."""
    marker = f"<!-- scamanager-auto-merge-pr:{pr_number} -->"
    pr_url = f"https://github.com/{repo_name}/pull/{pr_number}"
    return "\n".join([
        marker,
        "",
        "## ⚠️ Auto-Merge 실패",
        "",
        f"- **리포**: `{repo_name}`",
        f"- **PR**: [#{pr_number}]({pr_url})",
        f"- **점수**: {score}점 (기준 {threshold}점 이상)",
        f"- **실패 사유**: `{reason}`",
        "",
        "### 권장 조치",
        "",
        advice,
        "",
        "---",
        "<sub>Auto-generated by SCAManager auto-merge advisor</sub>",
    ])


async def create_merge_failure_issue(
    *,
    github_token: str,
    repo_name: str,
    pr_number: int,
    score: int,
    threshold: int,
    reason: str,
    advice: str,
) -> int | None:
    """24h 내 중복 체크 후 Issue 생성. 이미 존재하면 None, 생성 성공 시 Issue number."""
    dedup_marker = f"scamanager-auto-merge-pr:{pr_number}"
    title = f"[SCAManager] Auto-Merge 실패: #{pr_number} ({reason.split(':')[0].strip()})"
    body = _build_issue_body(
        repo_name=repo_name,
        pr_number=pr_number,
        score=score,
        threshold=threshold,
        reason=reason,
        advice=advice,
    )
    headers = github_api_headers(github_token)

    try:
        client = get_http_client()
        search_resp = await client.get(
            f"{GITHUB_API}/search/issues",
            params={
                "q": (
                    f'repo:{repo_name} "{dedup_marker}" in:body '
                    f"label:auto-merge-failure is:open"
                )
            },
            headers=headers,
        )
        search_resp.raise_for_status()
        if search_resp.json().get("total_count", 0) > 0:
            logger.info("Auto-merge failure Issue 이미 존재 (pr=%d)", pr_number)
            return None

        create_resp = await client.post(
            f"{GITHUB_API}/repos/{repo_name}/issues",
            json={"title": title, "body": body, "labels": ISSUE_LABELS},
            headers=headers,
        )
        create_resp.raise_for_status()
        number = create_resp.json().get("number")
        logger.info("Auto-merge failure Issue 생성 완료 #%s (pr=%d)", number, pr_number)
        return number
    except httpx.HTTPError as exc:
        logger.error("create_merge_failure_issue 실패 (%s, pr=%d): %s", repo_name, pr_number, exc)
        return None
