"""Railway 빌드 실패 시 GitHub Issue 자동 생성."""
import logging
import httpx
from src.constants import HTTP_CLIENT_TIMEOUT
from src.github_client.helpers import github_api_headers
from src.railway_client.models import RailwayDeployEvent

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"
ISSUE_LABELS = ["scamanager", "deploy-failure", "railway"]


def _build_issue_body(*, event: RailwayDeployEvent, logs_tail: str | None) -> str:
    """Railway 빌드 실패 Issue 본문을 조립한다."""
    marker = f"<!-- scamanager-railway-deployment-id:{event.deployment_id} -->"
    sha_short = event.commit_sha[:7] if event.commit_sha else "unknown"
    commit_url = (
        f"https://github.com/{event.repo_full_name}/commit/{event.commit_sha}"
        if event.repo_full_name and event.commit_sha
        else "#"
    )
    commit_line = event.commit_message.splitlines()[0] if event.commit_message else ""
    log_content = logs_tail if logs_tail else "로그를 가져오지 못했습니다. Railway 대시보드에서 확인해주세요."

    return "\n".join([
        marker,
        "",
        "## 🚨 Railway Build Failed",
        "",
        f"- **Project**: {event.project_name} (`{event.project_id}`)",
        f"- **Environment**: {event.environment_name}",
        f"- **Status**: {event.status}",
        f"- **Commit**: [`{sha_short}`]({commit_url}) — {commit_line}",
        f"- **Time**: {event.timestamp}",
        "",
        "### Build Log (last 200 lines)",
        "```",
        log_content,
        "```",
        "",
        "---",
        f'<sub>Auto-generated by SCAManager · <a href="https://railway.app/project/{event.project_id}">Railway 대시보드 열기</a></sub>',
    ])


async def create_deploy_failure_issue(
    *,
    github_token: str,
    repo_full_name: str,
    event: RailwayDeployEvent,
    logs_tail: str | None,
) -> int | None:
    """Issue 중복 체크 후 생성. 이미 존재하면 None, 생성 성공 시 Issue number."""
    marker = f"scamanager-railway-deployment-id:{event.deployment_id}"
    title = f"[SCAManager] Railway 빌드 실패: {event.project_name} ({event.status})"
    body = _build_issue_body(event=event, logs_tail=logs_tail)
    headers = github_api_headers(github_token)

    try:
        async with httpx.AsyncClient(timeout=HTTP_CLIENT_TIMEOUT) as client:
            # 중복 체크
            search_url = f"{GITHUB_API}/search/issues"
            search_resp = await client.get(
                search_url,
                params={"q": f'repo:{repo_full_name} "{marker}" in:body is:issue'},
                headers=headers,
            )
            search_resp.raise_for_status()
            if search_resp.json().get("total_count", 0) > 0:
                logger.info("Railway Issue 이미 존재 (deployment_id=%s)", event.deployment_id)
                return None

            # Issue 생성
            create_resp = await client.post(
                f"{GITHUB_API}/repos/{repo_full_name}/issues",
                json={"title": title, "body": body, "labels": ISSUE_LABELS},
                headers=headers,
            )
            create_resp.raise_for_status()
            number = create_resp.json().get("number")
            logger.info("Railway Issue 생성 완료 #%s (%s)", number, repo_full_name)
            return number
    except httpx.HTTPError as exc:
        logger.error("create_deploy_failure_issue 실패 (%s): %s", repo_full_name, exc)
        return None
