"""Railway 빌드 실패 시 GitHub Issue 자동 생성."""
import logging
import httpx
from src.constants import GITHUB_API
from src.github_client.helpers import github_api_headers
from src.i18n.loader import get_text
from src.railway_client.models import RailwayDeployEvent
from src.shared.http_client import get_http_client
from src.shared.log_safety import sanitize_for_log

logger = logging.getLogger(__name__)

ISSUE_LABELS = ["scamanager", "deploy-failure", "railway"]


def _build_issue_body(
    *, event: RailwayDeployEvent, logs_tail: str | None, language: str = "ko",
) -> str:
    """Railway 빌드 실패 Issue 본문을 조립한다.
    Build the Railway build-failure Issue body. language: repo 소유자 언어."""
    marker = f"<!-- scamanager-railway-deployment-id:{event.deployment_id} -->"
    sha_short = event.commit.commit_sha[:7] if event.commit.commit_sha else "unknown"
    commit_url = (
        f"https://github.com/{event.commit.repo_full_name}/commit/{event.commit.commit_sha}"
        if event.commit.repo_full_name and event.commit.commit_sha
        else "#"
    )
    commit_line = (
        event.commit.commit_message.splitlines()[0]
        if event.commit.commit_message
        else ""
    )
    log_content = logs_tail if logs_tail else get_text("notifier.railway.log_fetch_failed", language)

    return "\n".join([
        marker,
        "",
        "## 🚨 Railway Build Failed",
        "",
        f"- **Project**: {event.project.project_name} (`{event.project.project_id}`)",
        f"- **Environment**: {event.project.environment_name}",
        f"- **Status**: {event.status}",
        f"- **Commit**: [`{sha_short}`]({commit_url}) — {commit_line}",
        f"- **Time**: {event.timestamp}",
        "",
        "### Build Log (last 200 lines)",
        "```",
        log_content,
        "```",
        "",
        "---",
        f'<sub>Auto-generated by SCAManager · '
        f'<a href="https://railway.app/project/{event.project.project_id}">'
        f'{get_text("notifier.railway.dashboard_link", language)}</a></sub>',
    ])


async def create_deploy_failure_issue(
    *,
    github_token: str,
    repo_full_name: str,
    event: RailwayDeployEvent,
    logs_tail: str | None,
    language: str = "ko",
) -> int | None:
    """Issue 중복 체크 후 생성. 이미 존재하면 None, 생성 성공 시 Issue number.
    language: repo 소유자 언어 (제목/본문 i18n — [SCAManager] prefix 는 검색 호환 영문 고정)."""
    marker = f"scamanager-railway-deployment-id:{event.deployment_id}"
    # [SCAManager] prefix 영문 고정 (검색 호환) + 본문 사유는 i18n
    # [SCAManager] prefix stays English (searchability) + the reason is i18n'd
    build_failed = get_text("notifier.railway.build_failed", language)
    title = f"[SCAManager] {build_failed}: {event.project.project_name} ({event.status})"
    body = _build_issue_body(event=event, logs_tail=logs_tail, language=language)
    headers = github_api_headers(github_token)

    try:
        client = get_http_client()
        # 중복 체크
        # Deduplication check — skip creation if an issue with this marker already exists.
        search_url = f"{GITHUB_API}/search/issues"
        search_resp = await client.get(
            search_url,
            params={"q": f'repo:{repo_full_name} "{marker}" in:body is:issue'},
            headers=headers,
        )
        search_resp.raise_for_status()
        if search_resp.json().get("total_count", 0) > 0:
            logger.info("Railway Issue 이미 존재 (deployment_id=%s)", event.deployment_id)
            return None

        # Issue 생성
        create_resp = await client.post(
            f"{GITHUB_API}/repos/{repo_full_name}/issues",
            json={"title": title, "body": body, "labels": ISSUE_LABELS},
            headers=headers,
        )
        create_resp.raise_for_status()
        number = create_resp.json().get("number")
        logger.info("Railway Issue 생성 완료 #%s (%s)", number, sanitize_for_log(repo_full_name))
        return number
    except httpx.HTTPError:
        # Phase H PR-6A: logger.exception 으로 stack trace 보존
        logger.exception("create_deploy_failure_issue 실패 (%s)", sanitize_for_log(repo_full_name))
        return None
