#!/usr/bin/env python3
"""로컬 pre-commit 계층이 실제로 살아 있는지 — 관측면 (backlog R23, 2026-08-01).

## 왜 만드나 (실측)

`.pre-commit-config.yaml` 에 시크릿 훅 4종(gitleaks · commit-msg-secrets · env-not-staged ·
secrets-in-diff)이 정의돼 있는데, **설치돼 있지 않으면 하나도 실행되지 않는다.** 그리고
그 사실을 관측하는 면이 리포 전체에 없었다 — 회고 2026-07-31 실측: 창 22 커밋 내내
**0회 실행**. `.git/hooks/pre-commit` 이 없으면 `git commit` 은 아무 말 없이 성공한다.

🔴 CI 의 TruffleHog 는 이 계층을 **대체하지 못한다** — `--only-verified` 라 검증된 시크릿만
보고, 무엇보다 **커밋이 이미 원격에 올라간 뒤**다. pre-commit 의 값은 "올라가기 전에 막는 것"
이고, 그 값은 설치돼 있을 때만 존재한다.

## 계약 (advisory — 정책 17 안정성)

- 이 스크립트는 **exit 0** 이다. 로컬 환경 상태는 리포가 강제할 수 없고, 차단하면 새 PC·CI·
  타 개발자 환경에서 세션 시작 자체가 막힌다(가드 자살).
- 대신 **loud** 하게 알린다. SessionStart 훅 stdout 은 Claude 컨텍스트에 주입되므로,
  "설치돼 있지 않다" 가 매 세션 관측된다 — 관측면 0 이던 것을 관측 가능하게 만드는 것이 전부다.
- 🔴 **이것이 "보호" 가 아니라 "관측" 임을 명시한다.** advisory 를 보호로 읽으면 그 자체가
  observer-lie 다(AGENTS.md 불변식 1).

Observability only: reports whether the local pre-commit layer is actually installed. Always
exits 0 — the repo cannot enforce local machine state, and blocking would break fresh clones/CI.
CI's TruffleHog does not substitute: it runs after the push and only on verified secrets.
"""
from __future__ import annotations

import re
import subprocess  # nosec B404
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

_ROOT = Path(__file__).resolve().parents[1]


def git_hooks_dir(root: Path) -> Path | None:
    """이 작업트리의 실제 훅 디렉토리 — worktree 는 `.git` 이 파일이라 rev-parse 로 물어본다.
    Resolve the real hooks dir; in a worktree `.git` is a file, so ask git."""
    try:
        proc = subprocess.run(  # nosec B603 B607
            ["git", "rev-parse", "--git-path", "hooks"],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            cwd=str(root), timeout=30, check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    return (root / proc.stdout.strip()).resolve()


# ── pre-commit 생성 훅의 실제 형태 (2026-08-06 실물 생성 후 실측) ──────────
#
#   #!/bin/sh
#   # File generated by pre-commit: https://pre-commit.com
#   # ID: 138fd403232d2ddd5efb44317e38bf03
#   INSTALL_PYTHON='C:\...\python.exe'
#   ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
#   if [ -x "$INSTALL_PYTHON" ]; then exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
#
# 🔴 판정을 이 **구조**에서 끌어온다 — `"pre-commit" in text` 는 bare substring 이라
#    아래 4형태가 전부 "설치됨" 으로 통과했다(실측, tmp 픽스처):
#      `exit 0  # pre-commit disabled` · `echo 'pre-commit skipped'` ·
#      `: .git/hooks/pre-commit`(경로만 언급) — 즉 **아무것도 안 막는 훅이 활성으로 보였다**.
#    `guards.md` 가 명시적으로 금지한 형태이며, B8 floor 는 이 파일이 `subprocess` 를 쓰기
#    때문에 통과시켜 못 잡았다(그 '천장' 의 실사례).
# Decide from the generated script's structure; a bare substring check passed four
# neutralised-hook fixtures (measured), i.e. a hook that blocks nothing looked "installed".
_INVOKES_PRECOMMIT = re.compile(r"-mpre_commit\b")
_HOOK_IMPL = re.compile(r"\bhook-impl\b")
_HOOK_TYPE = re.compile(r"--hook-type=([a-z][a-z-]*)")
_INSTALL_PYTHON = re.compile(r"^INSTALL_PYTHON='([^']*)'", re.MULTILINE)

# 이 저장소가 **설치돼 있어야 한다고 보는** 훅 타입.
# 🔴 리터럴로 못박는다 — `.pre-commit-config.yaml` 에서 유도하면 그 키를 지우는 순간
#    "필요한 게 없으니 통과" 가 되어 자기참조 공허화다. 설정과의 정합은
#    `test_check_precommit_installed.py` 가 양방향으로 대조한다.
# Pinned literally: deriving it from the config would make deleting the config key pass.
REQUIRED_HOOK_TYPES = ("pre-commit", "commit-msg")


def _hook_health(hook: Path) -> tuple[bool, str | None]:
    """(pre-commit 이 설치한 살아있는 훅인가, 선언된 hook-type).

    🔴 인터프리터 **실재**까지 본다 — 생성된 훅은 절대 경로(`INSTALL_PYTHON`)를 박아 넣고
    그것이 없으면 `command -v pre-commit` 폴백으로 내려간다. 경로가 죽어 있으면 훅은
    형태상 멀쩡한데 실행은 실패한다.
    """
    if not hook.is_file():
        return False, None
    try:
        text = hook.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False, None
    if not (_INVOKES_PRECOMMIT.search(text) and _HOOK_IMPL.search(text)):
        return False, None
    m = _INSTALL_PYTHON.search(text)
    if m and not Path(m.group(1)).is_file():
        # 박아 넣은 인터프리터가 사라졌다 — 훅은 있는데 실행되지 않는다.
        return False, None
    t = _HOOK_TYPE.search(text)
    return True, (t.group(1) if t else None)


def installed_hook_types(hooks_dir: Path | None) -> set[str]:
    """실제로 살아 있는 pre-commit 훅 타입 집합.

    `.git/hooks/<type>` 파일을 읽어 **그 파일이 스스로 선언한** `--hook-type` 을 쓴다 —
    파일명으로 추정하지 않는다(이름만 바꿔 놓은 훅을 활성으로 오판하지 않기 위해).
    """
    if hooks_dir is None:
        return set()
    found: set[str] = set()
    for name in REQUIRED_HOOK_TYPES:
        healthy, declared = _hook_health(hooks_dir / name)
        if healthy and declared == name:
            found.add(name)
    return found


def hook_is_precommit(hooks_dir: Path | None) -> bool:
    """`pre-commit` 타입 훅이 살아 있는가 (하위 호환 이름 — 배선 테스트가 참조)."""
    return "pre-commit" in installed_hook_types(hooks_dir)


def pre_push_gate_installed(hooks_dir: Path | None) -> bool:
    """`.git/hooks/pre-push` 가 실재하고 **이 리포의 게이트 러너를 부르는지**.

    🔴 존재만 보면 안 된다 — 다른 도구가 남긴 훅일 수 있고 빈 파일일 수도 있다. 배선 판정이므로
    `scripts/pre_push_gate.py` 호출까지 확인한다.

    🔴 이 훅은 **git 이 추적하지 않는다**(머신 고유). 리포는 그 존재를 강제할 수 없고 **관측만**
    할 수 있으므로 그 한계를 출력에 명시한다. `.pre-commit-config.yaml` 에 `stages: [pre-push]`
    를 적는 방식은 pre-commit 이 그 훅 타입을 **따로 설치**해야 동작하므로, 미설치 머신에서는
    한 번도 안 도는 가드가 된다 — 2026-08-01 Grok 설계 검토(`019fbc8e`)가 그 안을 기각했다.
    Local hooks are untracked, so the repo can only observe this, never enforce it.
    """
    if hooks_dir is None:
        return False
    hook = hooks_dir / "pre-push"
    if not hook.is_file():
        return False
    try:
        return "pre_push_gate.py" in hook.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def main() -> int:
    """관측 결과를 보고한다 — **항상 exit 0**(advisory)."""
    present = installed_hook_types(git_hooks_dir(_ROOT))
    missing = [t for t in REQUIRED_HOOK_TYPES if t not in present]

    # 🔴 pre-push 게이트는 **별개 축**이다 — pre-commit 이 살아 있어도 이건 없을 수 있다.
    #    없으면 `pre_push_gate.py` 를 사람이 기억해서 돌려야 하고, 기억 의존은 이 리포가
    #    반복해 고쳐 온 실패 클래스다. 다만 로컬 훅은 추적 불가라 **관측만** 한다.
    # Separate axis: the pre-push gate can be absent even when pre-commit is healthy.
    if not pre_push_gate_installed(git_hooks_dir(_ROOT)):
        print(
            "ℹ️ pre-push 게이트 훅이 없습니다 — push 전 CI 가드가 **자동 실행되지 않습니다**.\n"
            "   No pre-push hook: the local CI-guard runner will not run automatically.\n"
            "   수동 / manual  : `py -3 scripts/pre_push_gate.py`\n"
            "   자동화 / automate: `.git/hooks/pre-push` 에 그 명령을 넣고 실행 권한 부여\n"
            "   ⚠️ 로컬 훅은 git 이 추적하지 않아 리포가 강제할 수 없습니다 — 관측만 합니다."
        )

    if not missing:
        print(f"✅ pre-commit 계층 활성 — 훅 타입 {', '.join(sorted(present))} 살아 있음")
        return 0

    # 🔴 **부분 설치를 부분으로 보고한다.** 예전에는 `pre-commit install` 만 치면 `commit-msg`
    #    타입이 빠졌고, 그러면 실제 토큰 유출 사고로 만들어진 `check-commit-msg-secrets` 만
    #    조용히 죽고 나머지는 설치돼 겉보기에는 "완료" 였다. 이전 판정은 그 상태를
    #    구별하지 못했다(pre-commit 타입만 봤다).
    #
    #    ⚠️ 2026-08-17 정정 — 위 문장이 현재형으로 적혀 있었으나 **지금은 그렇지 않다**:
    #    `.pre-commit-config.yaml:22` 의 `default_install_hook_types: [pre-commit, commit-msg]`
    #    가 맨 `install` 로 둘을 함께 설치한다(실측). 부분 설치가 여전히 가능한 경로는
    #    **`--hook-type` 을 명시하는 경우**다 — 명시가 그 기본값을 덮어 한 타입만 남긴다.
    #    그래서 이 부분 보고는 계속 필요하다. 바뀐 것은 원인이지 필요성이 아니다.
    # Historical: plain `install` used to omit commit-msg. Since default_install_hook_types was
    # added it installs both; partial installs now come from passing `--hook-type` explicitly.
    state = " · ".join(
        f"{t}={'✅' if t in present else '❌'}" for t in REQUIRED_HOOK_TYPES
    )
    print(
        "🔴 로컬 pre-commit 계층이 불완전합니다 — 아래 타입의 훅은 **실행되지 않습니다**.\n"
        "   The local pre-commit layer is incomplete; hooks of the missing types never run.\n"
        f"   훅 타입 / hook types : {state}\n"
        f"   누락 / missing      : {', '.join(missing)}\n"
        "   대상 훅 / affected  : gitleaks · check-commit-msg-secrets · check-env-not-staged ·\n"
        "                        check-secrets-in-diff · detect-private-key + 문서·가드 훅\n"
        "                        (`.pre-commit-config.yaml` 총 16종)\n"
        "   해결 / Fix:\n"
        "     py -3 -m pip install pre-commit\n"
        "     git config --unset-all core.hooksPath   # 설정돼 있으면 설치가 거부됩니다\n"
        "     py -3 -m pre_commit install             # 두 타입을 함께 설치합니다\n"
        "   ℹ️ `pre-commit` 이 PATH 에 없어도 됩니다 — 생성된 훅이 절대 인터프리터 경로를\n"
        "      박아 넣습니다. PATH 부재를 '미설치' 로 읽지 마세요.\n"
        "   🔴 CI 의 TruffleHog 는 대체가 아닙니다 — `--only-verified` 이고 **push 이후**입니다.\n"
        "   ⚠️ 이 검사는 advisory(비차단)입니다 — 관측면일 뿐 보호가 아닙니다."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
